// Phase 3 — DailyCommunication card + generateDailyCommunication() helper
//
// This is the FIRST card the customer (head teacher) actually sees. It is
// generated by AI from an ImportSnapshot + a SkillCard playbook.
//
// The TranslateCommand architecture lives as a top-level async function
// `generateDailyCommunication(...)` exported below. It is called from
// ImportSnapshotManager's UI trigger (Component context where
// `commandContext` is available via `this.args.context.commandContext`).
// We do NOT use a Command<I,O> class because Command.run() bodies don't
// have access to Component-only helpers like getCard/getCards.
//
// The visual layout mimics mockup 6/7 (Daily Communication — teacher-facing).
// Phase 4 will add the iPhone parent-facing view (mockup 8/9).

import {
  CardDef,
  FieldDef,
  field,
  contains,
  containsMany,
  Component,
} from 'https://cardstack.com/base/card-api';
import StringField from 'https://cardstack.com/base/string';
import DateField from 'https://cardstack.com/base/date';
import DatetimeField from 'https://cardstack.com/base/datetime';
import { tracked } from '@glimmer/tracking';
import { on } from '@ember/modifier';
import { eq } from '@cardstack/boxel-ui/helpers';
import SendRequestViaProxyCommand from '@cardstack/boxel-host/commands/send-request-via-proxy';
import { generateParentSummary } from './parent-daily-summary';

const DASHBOARD_URL =
  'https://app.boxel.ai/itp_project/tribecaprep-lms-v2-parent/TribecaPrepDashboard/main';

// ═════════════════════════════════════════════════════════
//   Nested FieldDef: one activity block in "WHAT I WORKED ON"
// ═════════════════════════════════════════════════════════

export class WorkedOnItemField extends FieldDef {
  static displayName = 'Worked On Item';
  @field subject = contains(StringField);      // Math / Reading / Services / Social Skills / etc
  @field description = contains(StringField);  // "DI Lesson 45: Counting patterns"
  @field score = contains(StringField);        // "18/20" or "30 min" or "" or "done"

  static embedded = class Embedded extends Component<typeof this> {
    <template>
      <div class='wo-row'>
        <span class='wo-subject'>{{@model.subject}}</span>
        <span class='wo-desc'>{{@model.description}}</span>
        {{#if @model.score}}
          <span class='wo-score'>{{@model.score}}</span>
        {{/if}}
      </div>
      <style scoped>
        .wo-row {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 10px 14px;
          background: #faf8f6;
          border-radius: 6px;
          font-size: 13px;
        }
        .wo-subject { font-weight: 600; color: #1a1816; min-width: 80px; }
        .wo-desc { color: #4a5568; flex: 1; }
        .wo-score { color: #2a9d8f; font-weight: 600; font-family: ui-monospace, monospace; font-size: 12px; }
      </style>
    </template>
  };

  // Edit format — each sub-field as an editable input so the teacher can
  // correct AI mistakes. Without this, the containsMany parent editor falls
  // back to embedded (read-only) for each item.
  static edit = class Edit extends Component<typeof this> {
    <template>
      <div class='wo-edit'>
        <div class='wo-edit-field'>
          <label>Subject</label>
          <@fields.subject />
        </div>
        <div class='wo-edit-field'>
          <label>Description (first-person)</label>
          <@fields.description />
        </div>
        <div class='wo-edit-field'>
          <label>Score (e.g. 18/20, 30 min, or empty)</label>
          <@fields.score />
        </div>
      </div>
      <style scoped>
        .wo-edit {
          display: flex;
          flex-direction: column;
          gap: 10px;
          padding: 12px 14px;
          background: #faf8f6;
          border-radius: 6px;
        }
        .wo-edit-field { display: flex; flex-direction: column; gap: 3px; }
        .wo-edit-field label {
          font-size: 10px;
          font-weight: 700;
          text-transform: uppercase;
          color: #718096;
          letter-spacing: 0.5px;
        }
      </style>
    </template>
  };
}

// ═════════════════════════════════════════════════════════
//   DailyCommunication — the card
// ═════════════════════════════════════════════════════════

export class DailyCommunication extends CardDef {
  static displayName = 'Daily Communication';

  // ── Identity / traceability (set by generateDailyCommunication) ──
  @field studentSlug = contains(StringField);
  @field studentName = contains(StringField);
  @field snapshotDate = contains(DateField);
  @field sourceSnapshotId = contains(StringField);
  @field sourceSkillCardId = contains(StringField);
  @field generatedAt = contains(DatetimeField);
  @field generatedBy = contains(StringField);

  // ── AI-generated content ──
  @field daySummary = contains(StringField);
  @field todayIAte = contains(StringField);
  @field myDayWas = contains(StringField);
  @field whatIWorkedOn = containsMany(WorkedOnItemField);
  @field todaysHighlight = contains(StringField);
  @field teacherNotes = contains(StringField);

  // ── Workflow state (not AI-generated) ──
  @field status = contains(StringField);             // 'draft' | 'reviewed' | 'sent'
  @field headTeacherName = contains(StringField);
  @field headTeacherRole = contains(StringField);
  @field homeNotes = contains(StringField);
  @field sentAt = contains(DatetimeField);

  // ── Computed ──
  // Phase 4 feeds this markdown to the parent-summary AI translator.
  // Single field, single read — same "one big markdown" principle as
  // ImportSnapshot.rawMarkdown and SkillCard.compiledPrompt.
  @field reviewedMarkdown = contains(StringField, {
    computeVia: function (this: DailyCommunication) {
      const lines: string[] = [];

      const rawName = String(this.studentName ?? this.studentSlug ?? '');
      const displayName = rawName && !/\s/.test(rawName) && rawName.includes('-')
        ? rawName
            .split('-')
            .map((w: string) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
            .join(' ')
        : rawName || 'Student';

      const dateStr = this.snapshotDate
        ? new Date(this.snapshotDate as any).toLocaleDateString('en-US', {
            weekday: 'long',
            month: 'long',
            day: 'numeric',
            year: 'numeric',
          })
        : '(no date)';

      lines.push('# Daily Communication - Reviewed');
      lines.push('');
      lines.push(`**Student:** ${displayName}`);
      lines.push(`**Date:** ${dateStr}`);
      if (this.daySummary) lines.push(`**Day summary:** ${this.daySummary}`);
      if (this.myDayWas) lines.push(`**My day was:** ${this.myDayWas}`);
      if (this.todayIAte) lines.push(`**Today I ate:** ${this.todayIAte}`);
      lines.push('');

      const worked = this.whatIWorkedOn ?? [];
      if (worked.length > 0) {
        lines.push('## What I Worked On');
        lines.push('');
        worked.forEach((w: any, i: number) => {
          const subject = w?.subject || '(no subject)';
          const desc = w?.description || '(no description)';
          const score = w?.score ? ` (${w.score})` : '';
          lines.push(`${i + 1}. **${subject}** — ${desc}${score}`);
        });
        lines.push('');
      }

      if (this.todaysHighlight) {
        lines.push("## Today's Highlight");
        lines.push('');
        lines.push(`"${this.todaysHighlight}"`);
        lines.push('');
      }

      if (this.teacherNotes) {
        lines.push('## Teacher Notes');
        lines.push('');
        lines.push(this.teacherNotes);
        lines.push('');
      }

      return lines.join('\n');
    },
  });

  // NOTE: override CardDef.cardTitle (the actual built-in field), not `title`.
  // Boxel host chrome reads cardTitle; overriding a non-existent `title` silently
  // falls through to "Untitled ${displayName}".
  @field cardTitle = contains(StringField, {
    computeVia: function (this: DailyCommunication) {
      const rawName = this.studentName || this.studentSlug || '';
      // Convert slug-form "jamie-chen" to display "Jamie Chen"
      const name = rawName && !/\s/.test(rawName) && rawName.includes('-')
        ? rawName
            .split('-')
            .map((w: string) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
            .join(' ')
        : (rawName || 'Student');
      const dateStr = this.snapshotDate
        ? new Date(this.snapshotDate as any).toLocaleDateString('en-US', {
            weekday: 'short',
            month: 'short',
            day: 'numeric',
          })
        : '';
      return dateStr ? `${name} - ${dateStr}` : `${name}'s Day`;
    },
  });

  // ─────────────────────────────────────────────────────
  // Embedded — snapshot list item
  // ─────────────────────────────────────────────────────
  static embedded = class Embedded extends Component<typeof DailyCommunication> {
    <template>
      <div class='dc-embed'>
        <div class='dc-embed-top'>
          <span class='dc-embed-title'>{{@model.studentName}}'s Day</span>
          <span class='dc-embed-date'>{{@model.snapshotDate}}</span>
        </div>
        <p class='dc-embed-summary'>{{@model.daySummary}}</p>
        <div class='dc-embed-bottom'>
          <span class='dc-embed-status status-{{@model.status}}'>{{@model.status}}</span>
          <span class='dc-embed-mood'>{{@model.myDayWas}}</span>
        </div>
      </div>
      <style scoped>
        .dc-embed {
          padding: 14px 16px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          font-family: system-ui, sans-serif;
        }
        .dc-embed-top {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          margin-bottom: 6px;
        }
        .dc-embed-title {
          font-weight: 600;
          color: #1a1816;
          font-size: 14px;
        }
        .dc-embed-date {
          font-size: 12px;
          color: #a0aec0;
          font-family: ui-monospace, monospace;
        }
        .dc-embed-summary {
          margin: 0 0 8px;
          font-size: 12px;
          line-height: 1.4;
          color: #4a5568;
          font-style: italic;
        }
        .dc-embed-bottom {
          display: flex;
          gap: 10px;
          align-items: center;
        }
        .dc-embed-status {
          font-size: 10px;
          padding: 2px 8px;
          border-radius: 999px;
          text-transform: uppercase;
          font-weight: 700;
          letter-spacing: 0.5px;
        }
        .status-draft { background: #fef5e7; color: #975a16; }
        .status-reviewed { background: #ebf8ff; color: #2c5282; }
        .status-sent { background: #f0fff4; color: #22543d; }
        .dc-embed-mood {
          font-size: 12px;
          color: #2a9d8f;
          font-weight: 600;
        }
      </style>
    </template>
  };

  // ─────────────────────────────────────────────────────
  // Isolated — mimics mockup 6/7 (teacher-facing daily communication)
  // ─────────────────────────────────────────────────────
  static isolated = class Isolated extends Component<typeof DailyCommunication> {
    dashboardUrl = DASHBOARD_URL;

    // NOTE: Teacher corrections are done via Boxel's built-in pencil icon in
    // the card's top-right chrome. It auto-generates a full edit form with
    // labeled inputs for all fields including containsMany nested items. No
    // custom edit button needed.

    // ── Phase 4: Parent Summary generation state ──
    @tracked psSkillCards: any[] = [];
    @tracked psSkillCardsLoading = true;
    @tracked psSelectedSkillCardId: string | null = null;
    @tracked psGenerateState: 'idle' | 'running' | 'success' | 'error' = 'idle';
    @tracked psGenerateMessage: string | null = null;
    @tracked psGenerateError: string | null = null;
    @tracked psLastGeneratedCardId: string | null = null;

    constructor(owner: any, args: any) {
      super(owner, args);
      this.loadParentSummarySkillCards();
    }

    get hostGetCards(): any {
      const argsAny = this.args as any;
      return (
        argsAny.context?.getCards ??
        argsAny.context?.actions?.getCards ??
        null
      );
    }

    get hostCommandContext(): any {
      const argsAny = this.args as any;
      return (
        argsAny.context?.commandContext ??
        argsAny.context?.actions?.commandContext ??
        null
      );
    }

    async unwrapCardsResource(resource: any, maxWaitMs = 8000): Promise<any[]> {
      try {
        const r: any = resource;
        if (Array.isArray(r)) return r;
        const readArr = (): any[] | null => {
          if (Array.isArray(r?.instances)) return r.instances;
          if (Array.isArray(r?.value)) return r.value;
          return null;
        };
        const start = Date.now();
        while (Date.now() - start < maxWaitMs) {
          const loading = r?.isLoading === true;
          const arr = readArr();
          if (!loading && arr !== null) return arr;
          await new Promise((res) => setTimeout(res, 100));
        }
        return readArr() ?? [];
      } catch (e) {
        console.error('[DC] unwrapCardsResource failed', e);
        return [];
      }
    }

    async loadParentSummarySkillCards() {
      this.psSkillCardsLoading = true;
      try {
        const getCards = this.hostGetCards;
        if (!getCards) return;
        const resource = getCards(
          this,
          () => ({
            filter: {
              type: {
                module: `${new URL('./skill-card', import.meta.url).href}`,
                name: 'SkillCard',
              },
            },
          }),
        );
        const arr = await this.unwrapCardsResource(resource);
        const filtered = arr.filter(
          (c: any) =>
            String(c?.category ?? '') === 'parent-summary' &&
            c?.isActive === true,
        );
        this.psSkillCards = filtered;
        if (filtered.length > 0 && !this.psSelectedSkillCardId) {
          this.psSelectedSkillCardId = String(filtered[0]?.id ?? '');
        }
        console.log(`[DC] loaded ${filtered.length} active parent-summary SkillCards`);
      } catch (e: any) {
        console.error('[DC] failed to load parent-summary skill cards', e);
      } finally {
        this.psSkillCardsLoading = false;
      }
    }

    handlePsSkillCardChange = (e: Event) => {
      this.psSelectedSkillCardId = (e.target as HTMLSelectElement).value;
    };

    handleGeneratePs = async () => {
      this.psGenerateState = 'running';
      this.psGenerateMessage = null;
      this.psGenerateError = null;
      this.psLastGeneratedCardId = null;

      try {
        const selectedSkill = this.psSkillCards.find(
          (c: any) => String(c?.id ?? '') === this.psSelectedSkillCardId,
        );
        if (!selectedSkill) {
          throw new Error('No parent-summary SkillCard selected');
        }
        const ctx = this.hostCommandContext;
        if (!ctx) throw new Error('commandContext unavailable');

        const realmHref = new URL('./', import.meta.url).href;

        const result = await generateParentSummary({
          dailyCommCard: this.args.model,
          skillCard: selectedSkill,
          commandContext: ctx,
          realmHref,
        });

        this.psGenerateState = 'success';
        this.psGenerateMessage = `Generated via ${result.model} in ${result.latencyMs}ms`;
        this.psLastGeneratedCardId = result.savedCardId;
      } catch (e: any) {
        console.error('[DC] generate parent summary failed', e);
        this.psGenerateState = 'error';
        this.psGenerateError = e?.message ?? String(e);
      }
    };

    get weekdayString() {
      if (!this.args.model?.snapshotDate) return '';
      const d = new Date(this.args.model.snapshotDate as any);
      return d.toLocaleDateString('en-US', { weekday: 'long' });
    }
    get dateString() {
      if (!this.args.model?.snapshotDate) return '';
      const d = new Date(this.args.model.snapshotDate as any);
      return d.toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      });
    }
    get moodCssClass() {
      const m = String(this.args.model?.myDayWas ?? '').toLowerCase();
      if (m === 'great') return 'mood-great';
      if (m === 'good') return 'mood-good';
      if (m === 'ok') return 'mood-ok';
      if (m === 'hard') return 'mood-hard';
      return 'mood-unknown';
    }
    get headTeacherInitials() {
      const s = String(this.args.model?.headTeacherName ?? '').trim();
      if (!s) return '';
      const parts = s.split(/\s+/);
      if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
      return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
    }

    <template>
      <a class='back-link' href={{this.dashboardUrl}}>
        ← Back to Dashboard
      </a>
      <article class='dc-root'>
        {{! ── Dark header bar ── }}
        <header class='dc-header-bar'>
          <div class='dc-brand'>
            <div class='dc-logo-box'>
              <svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                <path d='M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z'/>
              </svg>
            </div>
            <div class='dc-brand-text'>
              <span class='dc-school'>TRIBECA PREP</span>
              <span class='dc-label'>DAILY COMMUNICATION</span>
            </div>
          </div>
          <div class='dc-date-block'>
            <span class='dc-weekday'>{{this.weekdayString}}</span>
            <span class='dc-date'>{{this.dateString}}</span>
          </div>
        </header>

        {{! ── Student row: avatar + name + summary + sent badge ── }}
        <div class='dc-student-row'>
          <div class='dc-avatar'>
            <svg width='22' height='22' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
              <circle cx='12' cy='8' r='4'/>
              <path d='M4 21c0-4 4-7 8-7s8 3 8 7'/>
            </svg>
          </div>
          <div class='dc-student-meta'>
            <h1 class='dc-student-name'>{{@model.studentName}}'s Day</h1>
            <p class='dc-day-summary'>{{@model.daySummary}}</p>
          </div>
          {{#if (eq @model.status 'sent')}}
            <div class='dc-sent-badge'>
              <span class='check'>✓</span> Sent
            </div>
          {{/if}}
        </div>

        {{! ── Today I Ate + My Day Was ── }}
        <div class='dc-quick-row'>
          <div class='dc-quick-card'>
            <div class='dc-quick-label'>
              <svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                <circle cx='12' cy='12' r='8'/><path d='M9 10h.01M15 10h.01M9 15s1 2 3 2 3-2 3-2'/>
              </svg>
              TODAY I ATE
            </div>
            <div class='dc-quick-value'>{{@model.todayIAte}}</div>
          </div>
          <div class='dc-quick-card'>
            <div class='dc-quick-label'>
              <svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                <circle cx='12' cy='12' r='9'/><path d='M9 10h.01M15 10h.01M8 14c.5 1.5 2 3 4 3s3.5-1.5 4-3'/>
              </svg>
              MY DAY WAS
            </div>
            <div class='dc-quick-value {{this.moodCssClass}}'>{{@model.myDayWas}}</div>
          </div>
        </div>

        {{! ── What I Worked On ── }}
        <section class='dc-section'>
          <h3 class='dc-section-title'>
            <svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
              <rect x='3' y='4' width='18' height='16' rx='2'/><path d='M8 2v4M16 2v4M3 10h18'/>
            </svg>
            WHAT I WORKED ON
          </h3>
          <div class='dc-worked-list'>
            {{#each @model.whatIWorkedOn as |item|}}
              <div class='dc-worked-row'>
                <span class='dc-worked-subject'>{{item.subject}}</span>
                <span class='dc-worked-desc'>{{item.description}}</span>
                {{#if item.score}}
                  <span class='dc-worked-score'>{{item.score}}</span>
                {{/if}}
              </div>
            {{/each}}
          </div>
        </section>

        {{! ── Today's Highlight ── }}
        {{#if @model.todaysHighlight}}
          <section class='dc-highlight-section'>
            <h3 class='dc-section-title'>
              <svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                <polygon points='12 2 15 9 22 9 17 14 18 21 12 17 6 21 7 14 2 9 9 9 12 2'/>
              </svg>
              TODAY'S HIGHLIGHT
            </h3>
            <blockquote class='dc-highlight'>
              {{@model.todaysHighlight}}
            </blockquote>
          </section>
        {{/if}}

        {{! ── Teacher Notes ── }}
        {{#if @model.teacherNotes}}
          <section class='dc-section'>
            <h3 class='dc-section-title'>
              <svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                <path d='M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z'/><path d='M14 2v6h6M16 13H8M16 17H8M10 9H8'/>
              </svg>
              TEACHER NOTES
            </h3>
            <p class='dc-teacher-notes'>{{@model.teacherNotes}}</p>
            {{#if @model.headTeacherName}}
              <div class='dc-teacher-sig'>
                <span class='dc-teacher-initials'>
                  {{this.headTeacherInitials}}
                </span>
                <span class='dc-teacher-name'>{{@model.headTeacherName}}</span>
                <span class='dc-teacher-role'>{{@model.headTeacherRole}}</span>
              </div>
            {{/if}}
          </section>
        {{/if}}

        {{! ── Home Notes (parent input) ── }}
        <section class='dc-section dc-home-section'>
          <h3 class='dc-section-title'>
            <svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
              <path d='M3 12l9-8 9 8'/><path d='M5 10v10h14V10'/>
            </svg>
            HOME NOTES
          </h3>
          {{#if @model.homeNotes}}
            <p class='dc-home-notes-text'>{{@model.homeNotes}}</p>
          {{else}}
            <p class='dc-home-notes-placeholder'>
              <em>Share what happened at home or notes for tomorrow...</em>
            </p>
          {{/if}}
          <div class='dc-signature-line'>
            <span class='dc-sig-label'>Parent/Guardian Signature</span>
          </div>
        </section>

        {{! ── Phase 4: Generate Parent Summary actions ── }}
        <section class='dc-ps-actions'>
          <h3 class='dc-section-title'>
            NEXT STEP — GENERATE PARENT SUMMARY
          </h3>
          <p class='dc-ps-intro'>
            Once you've reviewed this Daily Communication, generate the
            parent-facing mobile summary. A second AI call will condense this
            card into the format parents see on their phone.
          </p>

          <div class='dc-ps-row'>
            <label class='dc-ps-label'>Playbook:</label>
            {{#if this.psSkillCardsLoading}}
              <span class='dc-ps-note'>Loading parent-summary SkillCards...</span>
            {{else if (eq this.psSkillCards.length 0)}}
              <span class='dc-ps-error'>
                No active parent-summary SkillCard found. Check
                SkillCard/parent-summary-generator.json exists and isActive is true.
              </span>
            {{else}}
              <select {{on 'change' this.handlePsSkillCardChange}}>
                {{#each this.psSkillCards as |sc|}}
                  <option value={{sc.id}} selected={{eq sc.id this.psSelectedSkillCardId}}>
                    {{sc.name}} ({{sc.version}})
                  </option>
                {{/each}}
              </select>
            {{/if}}
          </div>

          <button
            type='button'
            class='dc-ps-btn'
            disabled={{eq this.psGenerateState 'running'}}
            {{on 'click' this.handleGeneratePs}}
          >
            {{#if (eq this.psGenerateState 'running')}}
              Generating Parent Summary...
            {{else}}
              Generate Parent Summary
            {{/if}}
          </button>

          {{#if (eq this.psGenerateState 'success')}}
            <div class='dc-ps-banner success'>
              <strong>SUCCESS</strong> {{this.psGenerateMessage}}
              {{#if this.psLastGeneratedCardId}}
                <div class='dc-ps-link'>
                  <a href={{this.psLastGeneratedCardId}} target='_blank' rel='noopener'>
                    Open ParentDailySummary →
                  </a>
                </div>
              {{/if}}
            </div>
          {{/if}}

          {{#if (eq this.psGenerateState 'error')}}
            <div class='dc-ps-banner error'>
              <strong>ERROR</strong>
              <pre>{{this.psGenerateError}}</pre>
            </div>
          {{/if}}
        </section>

        {{! ── Debug footer: traceability ── }}
        <footer class='dc-footer'>
          <details>
            <summary>Generation metadata</summary>
            <dl>
              <dt>Generated at</dt><dd>{{@model.generatedAt}}</dd>
              <dt>Model</dt><dd class='mono'>{{@model.generatedBy}}</dd>
              <dt>Source snapshot</dt><dd class='mono small'>{{@model.sourceSnapshotId}}</dd>
              <dt>Playbook</dt><dd class='mono small'>{{@model.sourceSkillCardId}}</dd>
              <dt>Status</dt><dd>{{@model.status}}</dd>
            </dl>
          </details>
        </footer>
      </article>

      <style scoped>
        .back-link {
          display: inline-block;
          margin: 16px auto 12px;
          max-width: 720px;
          width: 100%;
          padding: 8px 14px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          color: #4a5568;
          font-family: system-ui, sans-serif;
          font-size: 12px;
          font-weight: 600;
          text-decoration: none;
          box-sizing: border-box;
        }
        .back-link:hover {
          background: #faf8f6;
          border-color: #2a9d8f;
          color: #2a9d8f;
        }
        .dc-root {
          max-width: 720px;
          margin: 0 auto;
          padding: 0;
          background: white;
          font-family: system-ui, -apple-system, sans-serif;
          color: #1a1816;
          border-radius: 12px;
          overflow: hidden;
          box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
        }

        /* ── Dark header ── */
        .dc-header-bar {
          background: #1e1e2a;
          color: white;
          padding: 18px 24px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .dc-brand {
          display: flex;
          align-items: center;
          gap: 12px;
        }
        .dc-logo-box {
          width: 34px;
          height: 34px;
          background: #e05d50;
          border-radius: 8px;
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
        }
        .dc-brand-text {
          display: flex;
          flex-direction: column;
          gap: 2px;
        }
        .dc-school {
          font-size: 11px;
          font-weight: 700;
          color: #e05d50;
          letter-spacing: 0.8px;
        }
        .dc-label {
          font-size: 10px;
          font-weight: 600;
          color: #a0a0b0;
          letter-spacing: 0.6px;
        }
        .dc-date-block {
          display: flex;
          flex-direction: column;
          align-items: flex-end;
          gap: 2px;
        }
        .dc-weekday {
          font-size: 15px;
          font-weight: 700;
        }
        .dc-date {
          font-size: 11px;
          color: #a0a0b0;
        }

        /* ── Student row ── */
        .dc-student-row {
          display: flex;
          align-items: center;
          gap: 14px;
          padding: 24px;
          border-bottom: 1px solid #f5f2ef;
        }
        .dc-avatar {
          width: 48px;
          height: 48px;
          background: #2a9d8f;
          color: white;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }
        .dc-student-meta { flex: 1; }
        .dc-student-name {
          margin: 0 0 4px;
          font-size: 20px;
          font-weight: 700;
          color: #1a1816;
        }
        .dc-day-summary {
          margin: 0;
          color: #5c5650;
          font-size: 13px;
          line-height: 1.5;
        }
        .dc-sent-badge {
          background: #e8f6f4;
          color: #2a9d8f;
          padding: 6px 12px;
          border-radius: 999px;
          font-size: 12px;
          font-weight: 700;
          display: flex;
          align-items: center;
          gap: 4px;
          flex-shrink: 0;
        }
        .dc-sent-badge .check { font-size: 13px; }

        /* ── Quick row: Today I Ate + My Day Was ── */
        .dc-quick-row {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 12px;
          padding: 20px 24px;
          border-bottom: 1px solid #f5f2ef;
        }
        .dc-quick-card {
          background: #faf8f6;
          border-radius: 8px;
          padding: 14px 16px;
        }
        .dc-quick-label {
          display: flex;
          align-items: center;
          gap: 6px;
          font-size: 10px;
          font-weight: 700;
          color: #8a8279;
          letter-spacing: 0.6px;
          margin-bottom: 6px;
        }
        .dc-quick-value {
          font-size: 14px;
          color: #1a1816;
          font-weight: 600;
        }
        .dc-quick-value.mood-great { color: #2a9d8f; }
        .dc-quick-value.mood-good { color: #38a169; }
        .dc-quick-value.mood-ok { color: #c08b30; }
        .dc-quick-value.mood-hard { color: #e05d50; }

        /* ── Sections ── */
        .dc-section {
          padding: 20px 24px;
          border-bottom: 1px solid #f5f2ef;
        }
        .dc-section:last-of-type { border-bottom: none; }
        .dc-section-title {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 10px;
          font-weight: 700;
          color: #8a8279;
          letter-spacing: 0.8px;
          margin: 0 0 12px;
        }

        /* ── What I Worked On ── */
        .dc-worked-list {
          display: flex;
          flex-direction: column;
          gap: 1px;
          background: #f5f2ef;
          border-radius: 8px;
          overflow: hidden;
        }
        .dc-worked-row {
          display: grid;
          grid-template-columns: 100px 1fr auto;
          align-items: center;
          gap: 12px;
          padding: 14px 16px;
          background: white;
        }
        .dc-worked-subject {
          font-weight: 600;
          color: #1a1816;
          font-size: 13px;
        }
        .dc-worked-desc {
          color: #5c5650;
          font-size: 13px;
        }
        .dc-worked-score {
          background: #e8f6f4;
          color: #2a9d8f;
          padding: 4px 10px;
          border-radius: 6px;
          font-weight: 700;
          font-size: 12px;
          font-family: ui-monospace, monospace;
        }

        /* ── Highlight block ── */
        .dc-highlight-section {
          padding: 20px 24px;
          border-bottom: 1px solid #f5f2ef;
        }
        .dc-highlight {
          margin: 0;
          padding: 16px 20px;
          background: #e8f6f4;
          border-left: 4px solid #2a9d8f;
          border-radius: 0 8px 8px 0;
          color: #1a1816;
          font-size: 14px;
          font-style: italic;
          line-height: 1.6;
        }

        /* ── Teacher notes ── */
        .dc-teacher-notes {
          margin: 0 0 14px;
          color: #2d3748;
          font-size: 14px;
          line-height: 1.6;
        }
        .dc-teacher-sig {
          display: flex;
          align-items: center;
          gap: 10px;
          padding-top: 10px;
          border-top: 1px dashed #e2e8f0;
        }
        .dc-teacher-initials {
          width: 28px;
          height: 28px;
          background: #2a9d8f;
          color: white;
          border-radius: 6px;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          font-size: 11px;
          font-weight: 700;
        }
        .dc-teacher-name {
          font-weight: 600;
          color: #1a1816;
          font-size: 13px;
        }
        .dc-teacher-role {
          color: #8a8279;
          font-size: 12px;
        }

        /* ── Home notes ── */
        .dc-home-section { background: #faf8f6; }
        .dc-home-notes-placeholder {
          margin: 0 0 20px;
          padding: 12px 14px;
          background: white;
          border: 1px dashed #e2e8f0;
          border-radius: 8px;
          color: #a0aec0;
          font-size: 13px;
        }
        .dc-home-notes-text {
          margin: 0 0 20px;
          padding: 12px 14px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          color: #2d3748;
          font-size: 13px;
          line-height: 1.5;
        }
        .dc-signature-line {
          display: flex;
          align-items: center;
          gap: 10px;
          padding-top: 4px;
        }
        .dc-sig-label {
          font-size: 10px;
          color: #8a8279;
          font-weight: 600;
          letter-spacing: 0.5px;
        }
        .dc-signature-line::after {
          content: '';
          flex: 1;
          border-bottom: 1px dashed #cbd5e0;
        }

        /* ── Phase 4: Parent Summary actions bar ── */
        .dc-ps-actions {
          padding: 20px 24px;
          background: #e8f6f4;
          border-top: 2px solid #2a9d8f;
        }
        .dc-ps-intro {
          font-size: 12px;
          color: #4a5568;
          line-height: 1.5;
          margin: 0 0 12px;
        }
        .dc-ps-row {
          display: flex;
          align-items: center;
          gap: 12px;
          margin-bottom: 12px;
        }
        .dc-ps-label {
          font-size: 11px;
          font-weight: 700;
          color: #4a5568;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          min-width: 64px;
        }
        .dc-ps-row select {
          flex: 1;
          padding: 8px 12px;
          border: 1px solid #cbd5e0;
          border-radius: 6px;
          font-size: 13px;
          background: white;
        }
        .dc-ps-note { color: #718096; font-size: 12px; }
        .dc-ps-error { color: #c53030; font-size: 12px; }
        .dc-ps-btn {
          padding: 10px 20px;
          background: #2a9d8f;
          color: white;
          border: none;
          border-radius: 6px;
          font-size: 13px;
          font-weight: 700;
          cursor: pointer;
        }
        .dc-ps-btn:disabled { background: #cbd5e0; cursor: wait; }
        .dc-ps-btn:not(:disabled):hover { background: #238077; }
        .dc-ps-banner {
          margin-top: 12px;
          padding: 12px 14px;
          border-radius: 6px;
          font-size: 12px;
        }
        .dc-ps-banner.success {
          background: #f0fff4;
          border: 1px solid #38a169;
          color: #22543d;
        }
        .dc-ps-banner.error {
          background: #fff5f5;
          border: 1px solid #e53e3e;
          color: #742a2a;
        }
        .dc-ps-banner pre {
          margin: 6px 0 0;
          font-family: ui-monospace, monospace;
          font-size: 11px;
          white-space: pre-wrap;
          word-break: break-word;
        }
        .dc-ps-link { margin-top: 6px; }
        .dc-ps-link a {
          color: #2b6cb0;
          text-decoration: none;
          font-weight: 600;
          font-family: ui-monospace, monospace;
          font-size: 12px;
        }
        .dc-ps-link a:hover { text-decoration: underline; }

        /* ── Footer / debug ── */
        .dc-footer {
          padding: 14px 24px;
          background: #faf8f6;
          font-size: 11px;
          color: #8a8279;
        }
        .dc-footer details summary {
          cursor: pointer;
          font-weight: 600;
        }
        .dc-footer dl {
          margin: 10px 0 0;
          display: grid;
          grid-template-columns: 110px 1fr;
          gap: 4px 12px;
          font-size: 11px;
        }
        .dc-footer dt { color: #8a8279; }
        .dc-footer dd { margin: 0; color: #2d3748; word-break: break-all; }
        .dc-footer dd.mono { font-family: ui-monospace, monospace; }
        .dc-footer dd.small { font-size: 10px; }
      </style>
    </template>
  };
}

// ═════════════════════════════════════════════════════════
//   generateDailyCommunication — the actual AI translate flow
//
//   Called from ImportSnapshotManager's UI button. Reads
//   snapshot.rawMarkdown + skillCard.compiledPrompt, calls Gemini via
//   SendRequestViaProxyCommand, parses JSON, constructs + saves a new
//   DailyCommunication card.
// ═════════════════════════════════════════════════════════

export interface GenerateInput {
  // The already-loaded card instances (Component passes them in from model.snapshots + loaded skillCards)
  snapshotCard: any;      // ImportSnapshot instance
  skillCard: any;         // SkillCard instance
  // Host context for commandContext (required by SendRequestViaProxyCommand)
  commandContext: any;
  // parent-daily realm URL where the new DailyCommunication will be saved
  realmHref: string;
}

export interface GenerateResult {
  savedCardId: string;
  model: string;
  latencyMs: number;
  parsedJson: any;
}

export async function generateDailyCommunication(
  input: GenerateInput,
): Promise<GenerateResult> {
  const t0 = performance.now();

  // ── 1. Extract the playbook + the raw observation markdown ──
  const compiledPrompt = String(input.skillCard?.compiledPrompt ?? '').trim();
  const rawMarkdown = String(input.snapshotCard?.rawMarkdown ?? '').trim();

  if (!compiledPrompt) {
    throw new Error(
      'SkillCard compiledPrompt is empty. Check the SkillCard instance.',
    );
  }
  if (!rawMarkdown) {
    throw new Error(
      'ImportSnapshot rawMarkdown is empty. Fetch a snapshot first.',
    );
  }

  // ── 2. Build the system prompt: playbook + append OUTPUT SCHEMA ──
  const outputSchemaInstruction = `

---

## YOUR TASK

You will be given the teacher's raw observation snapshot for one student on
one day. The snapshot includes observations, today's schedule (from daily plan),
and active learning goals. Rewrite it into a warm daily communication that
strictly follows the playbook above.

Return ONLY a valid JSON object matching the schema below. No markdown fences,
no commentary outside the JSON. All text fields must respect the Tone
Guidelines, Prohibited Terms, and Vocabulary Overrides from the playbook.

### OUTPUT SCHEMA

{
  "daySummary": "<one warm sentence capturing the feeling of the student's day>",
  "todayIAte":  "<one short phrase about food/snack if the snapshot mentions it, otherwise 'Not recorded today'>",
  "myDayWas":   "<one of: Great | Good | OK | Hard>",
  "whatIWorkedOn": [
    {
      "subject":     "<domain: Math, Reading, Language, Services, Social Skills, etc.>",
      "description": "<what the student worked on, parent-friendly language, reference the actual activity from schedule/observations>",
      "score":       "<score from observations like '4/5', '8/10', or a check mark '✓' for completed, or '30 min' for duration>"
    }
  ],
  "todaysHighlight": "<a first-person quoted highlight from the child's perspective; pick the best/warmest moment from observations>",
  "teacherNotes":    "<a 2-4 sentence narrative from teacher's warm perspective. Reference specific scores and activities. Mention progress toward learning goals if relevant.>"
}

### RULES

1. If the snapshot is empty, set daySummary to "No observations recorded today" and leave text fields empty strings.
2. The "whatIWorkedOn" array should include ONE entry per academic activity that has a score or was completed. Use the schedule timeline to know the order and the observations for details/scores.
3. Include routine activities (Homeroom, Sensory Break) only if the observations mention something noteworthy about them.
4. "todaysHighlight" must be written as the student speaking in first person — pick the warmest or most impressive moment.
5. "teacherNotes" is where the teacher speaks ABOUT the child (third person). Reference actual scores and learning goal progress.
6. Never mention the student's name in the body text.
7. Use the Active Learning Goals section to understand what the student is working toward — reference goal progress in teacherNotes if observations show improvement.`;

  const systemPrompt = compiledPrompt + outputSchemaInstruction;

  const userPrompt =
    'Here is today\'s raw observation snapshot. Generate the daily communication JSON:\n\n' +
    rawMarkdown;

  // ── 3. Decide model from SkillCard.modelSize (fallback to known-good) ──
  const modelFromSkill = String(input.skillCard?.modelSize ?? '').trim();
  const model =
    modelFromSkill && modelFromSkill.startsWith('google/')
      ? modelFromSkill
      : 'google/gemini-2.0-flash-001';

  console.log(`[generateDC] using model=${model}, systemPrompt len=${systemPrompt.length}, userPrompt len=${userPrompt.length}`);

  // ── 4. Call Gemini via Boxel proxy ──
  const requestBody = JSON.stringify({
    model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt },
    ],
    temperature: 0.4,
    max_tokens: 1200,
  });

  const apiCall = new SendRequestViaProxyCommand(input.commandContext).execute({
    url: 'https://openrouter.ai/api/v1/chat/completions',
    method: 'POST',
    requestBody,
    headers: {
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://app.boxel.ai',
      'X-Title': 'Tribeca Prep Daily Communication Generator',
    },
  });

  const timeout = new Promise((_r, rej) =>
    setTimeout(() => rej(new Error('AI translate timed out after 30s')), 30000),
  );

  const response: any = await Promise.race([apiCall, timeout]);

  if (response?.response && !response.response.ok) {
    let bodyText = '';
    try { bodyText = await response.response.text(); } catch (_) {}
    throw new Error(
      `HTTP ${response.response.status}: ${response.response.statusText} body: ${bodyText.slice(0, 800)}`,
    );
  }

  // ── 5. Unwrap the response (multi-shape) and extract content ──
  let data: any;
  try {
    if (response?.response?.text) {
      const raw = await response.response.text();
      data = JSON.parse(raw);
    } else if (response?.response?.json) {
      data = await response.response.json();
    } else {
      data = response;
    }
  } catch (_) {
    data = response;
  }

  let content: string =
    data?.choices?.[0]?.message?.content ??
    data?.response?.choices?.[0]?.message?.content ??
    data?.data?.choices?.[0]?.message?.content ??
    (typeof data?.response === 'string' ? data.response : '') ??
    '';

  if (!content && data) {
    try {
      const jsonStr = typeof data === 'string' ? data : JSON.stringify(data);
      const match = jsonStr.match(/"content"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      if (match) content = JSON.parse('"' + match[1] + '"');
    } catch (_) { /* ignore */ }
  }

  const clean = content
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/i, '')
    .trim();

  if (!clean) {
    throw new Error(
      `AI returned empty content. Response keys: ${Object.keys(data ?? {}).join(',')}`,
    );
  }

  let parsed: any;
  try {
    parsed = JSON.parse(clean);
  } catch (e) {
    throw new Error(
      `Failed to parse AI response as JSON: ${e}. Raw content: ${clean.slice(0, 600)}`,
    );
  }

  console.log('[generateDC] parsed JSON', parsed);

  // ── 6. Build the DailyCommunication card ──
  const dc = new DailyCommunication();

  // Traceability (set by command)
  dc.studentSlug = String(input.snapshotCard?.studentSlug ?? '');
  // Convert slug-form "jamie-chen" to display "Jamie Chen" if the stored
  // studentName is actually a slug (ImportSnapshot loadStudents may have
  // fallen back to slug when cross-realm Student firstName/lastName couldn't
  // be resolved synchronously).
  const rawStudentName = String(input.snapshotCard?.studentName ?? '');
  const looksLikeSlug =
    rawStudentName && !/\s/.test(rawStudentName) && rawStudentName.includes('-');
  dc.studentName = looksLikeSlug
    ? rawStudentName
        .split('-')
        .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
        .join(' ')
    : rawStudentName;
  // snapshotDate must be a Date instance
  const snapDate = input.snapshotCard?.snapshotDate;
  if (snapDate instanceof Date) {
    (dc as any).snapshotDate = snapDate;
  } else if (typeof snapDate === 'string') {
    (dc as any).snapshotDate = new Date(snapDate);
  } else {
    (dc as any).snapshotDate = new Date();
  }
  dc.sourceSnapshotId = String(input.snapshotCard?.id ?? '');
  dc.sourceSkillCardId = String(input.skillCard?.id ?? '');
  (dc as any).generatedAt = new Date();
  dc.generatedBy = model;

  // AI-generated content
  dc.daySummary = String(parsed?.daySummary ?? '');
  dc.todayIAte = String(parsed?.todayIAte ?? '');
  dc.myDayWas = String(parsed?.myDayWas ?? '');
  dc.todaysHighlight = String(parsed?.todaysHighlight ?? '');
  dc.teacherNotes = String(parsed?.teacherNotes ?? '');

  // whatIWorkedOn containsMany — populate via direct assignment of plain objects
  // (Boxel will coerce to WorkedOnItemField instances)
  const workedRaw = Array.isArray(parsed?.whatIWorkedOn)
    ? parsed.whatIWorkedOn
    : [];
  (dc as any).whatIWorkedOn = workedRaw.map((w: any) => {
    const item = new WorkedOnItemField();
    item.subject = String(w?.subject ?? '');
    item.description = String(w?.description ?? '');
    item.score = String(w?.score ?? '');
    return item;
  });

  // Workflow state
  dc.status = 'draft';
  dc.headTeacherName = 'V. Petrov'; // placeholder, will be real user in Phase 5
  dc.headTeacherRole = 'Head Teacher';
  dc.homeNotes = '';

  // ── 7. Save to parent-daily realm ──
  const { default: SaveCardCommand } = await import(
    '@cardstack/boxel-host/commands/save-card'
  );

  const saveResult: any = await new SaveCardCommand(input.commandContext).execute({
    card: dc,
    realm: input.realmHref,
  });

  const savedCardId =
    saveResult?.savedCard?.id ?? saveResult?.id ?? (dc as any)?.id ?? '';

  const latencyMs = Math.round(performance.now() - t0);
  console.log(`[generateDC] saved DailyCommunication id=${savedCardId} in ${latencyMs}ms`);

  return {
    savedCardId,
    model,
    latencyMs,
    parsedJson: parsed,
  };
}
