// Phase 4 - ParentDailySummary card + generateParentSummary helper
//
// This is the FINAL customer-facing deliverable - a mobile-optimized summary
// parents scan on their phone at 3:30 PM. It is generated by AI from a
// reviewed DailyCommunication (Phase 3 output) using a parent-summary
// SkillCard playbook.
//
// Pipeline position:
//   ImportSnapshot -> DailyCommunication (Phase 3) -> ParentDailySummary (Phase 4)
//
// Visual layout mimics mockup 8/9 (iPhone mobile vertical view).

import {
  CardDef,
  FieldDef,
  field,
  contains,
  containsMany,
  Component,
} from 'https://cardstack.com/base/card-api';
import StringField from 'https://cardstack.com/base/string';
import DateField from 'https://cardstack.com/base/date';
import DatetimeField from 'https://cardstack.com/base/datetime';
import { eq } from '@cardstack/boxel-ui/helpers';
import SendRequestViaProxyCommand from '@cardstack/boxel-host/commands/send-request-via-proxy';

const DASHBOARD_URL =
  'https://app.boxel.ai/itp_project/tribecaprep-lms-v2-parent/TribecaPrepDashboard/main';

// =========================================================
//   Nested FieldDef classes
// =========================================================

export class HighlightBlockField extends FieldDef {
  static displayName = 'Highlight Block';
  @field type = contains(StringField);         // Academic | Social | Behavioral
  @field title = contains(StringField);        // 2-4 word title
  @field description = contains(StringField);  // 1 sentence

  static embedded = class Embedded extends Component<typeof this> {
    <template>
      <div class='hb-embed hb-{{@model.type}}'>
        <div class='hb-title'>{{@model.title}}</div>
        <div class='hb-desc'>{{@model.description}}</div>
      </div>
      <style scoped>
        .hb-embed {
          padding: 12px 14px;
          border-radius: 12px;
          font-family: system-ui, sans-serif;
        }
        .hb-title { font-weight: 700; font-size: 13px; margin-bottom: 4px; }
        .hb-desc { font-size: 12px; line-height: 1.4; }
        .hb-Academic { background: #fdeceb; color: #9a2d1f; }
        .hb-Social { background: #f1ebfb; color: #553c9a; }
        .hb-Behavioral { background: #fef5e7; color: #975a16; }
      </style>
    </template>
  };

  static edit = class Edit extends Component<typeof this> {
    <template>
      <div class='hb-edit'>
        <div class='hb-edit-field'>
          <label>Type (Academic / Social / Behavioral)</label>
          <@fields.type />
        </div>
        <div class='hb-edit-field'>
          <label>Title (2-4 words)</label>
          <@fields.title />
        </div>
        <div class='hb-edit-field'>
          <label>Description (one sentence, first-person)</label>
          <@fields.description />
        </div>
      </div>
      <style scoped>
        .hb-edit {
          display: flex;
          flex-direction: column;
          gap: 10px;
          padding: 12px 14px;
          background: #faf8f6;
          border-radius: 8px;
        }
        .hb-edit-field { display: flex; flex-direction: column; gap: 3px; }
        .hb-edit-field label {
          font-size: 10px;
          font-weight: 700;
          text-transform: uppercase;
          color: #718096;
          letter-spacing: 0.5px;
        }
      </style>
    </template>
  };
}

export class TimelineEntryField extends FieldDef {
  static displayName = 'Timeline Entry';
  @field time = contains(StringField);      // HH:MM
  @field activity = contains(StringField);  // short label
  @field status = contains(StringField);    // optional short descriptor
  @field score = contains(StringField);     // optional score/duration

  static embedded = class Embedded extends Component<typeof this> {
    <template>
      <div class='te-embed'>
        <span class='te-time'>{{@model.time}}</span>
        <span class='te-dot'></span>
        <span class='te-activity'>{{@model.activity}}</span>
        {{#if @model.score}}
          <span class='te-score'>{{@model.score}}</span>
        {{/if}}
        {{#if @model.status}}
          <span class='te-status'>{{@model.status}}</span>
        {{/if}}
      </div>
      <style scoped>
        .te-embed {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 6px 0;
          font-size: 13px;
        }
        .te-time { color: #718096; font-family: ui-monospace, monospace; font-size: 12px; min-width: 44px; }
        .te-dot { width: 8px; height: 8px; border-radius: 50%; background: #2a9d8f; flex-shrink: 0; }
        .te-activity { color: #1a1816; flex: 1; }
        .te-score { background: #e8f6f4; color: #2a9d8f; font-family: ui-monospace, monospace; font-size: 11px; padding: 2px 8px; border-radius: 6px; }
        .te-status { color: #7c5fc4; font-size: 11px; font-style: italic; }
      </style>
    </template>
  };

  static edit = class Edit extends Component<typeof this> {
    <template>
      <div class='te-edit'>
        <div class='te-edit-field'>
          <label>Time (HH:MM, e.g. 09:00)</label>
          <@fields.time />
        </div>
        <div class='te-edit-field'>
          <label>Activity (1-3 words)</label>
          <@fields.activity />
        </div>
        <div class='te-edit-field'>
          <label>Status (optional)</label>
          <@fields.status />
        </div>
        <div class='te-edit-field'>
          <label>Score (optional)</label>
          <@fields.score />
        </div>
      </div>
      <style scoped>
        .te-edit {
          display: flex;
          flex-direction: column;
          gap: 10px;
          padding: 12px 14px;
          background: #faf8f6;
          border-radius: 8px;
        }
        .te-edit-field { display: flex; flex-direction: column; gap: 3px; }
        .te-edit-field label {
          font-size: 10px;
          font-weight: 700;
          text-transform: uppercase;
          color: #718096;
          letter-spacing: 0.5px;
        }
      </style>
    </template>
  };
}

// TomorrowItemField: AI does NOT fill this. Teacher fills it manually
// (Phase 5 wiring TBD). We keep the schema so the card has a slot.
export class TomorrowItemField extends FieldDef {
  static displayName = 'Tomorrow Item';
  @field icon = contains(StringField);   // emoji or short icon hint
  @field text = contains(StringField);   // "Return library book"

  static embedded = class Embedded extends Component<typeof this> {
    <template>
      <div class='ti-embed'>
        <span class='ti-icon'>{{@model.icon}}</span>
        <span class='ti-text'>{{@model.text}}</span>
      </div>
      <style scoped>
        .ti-embed {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 10px 14px;
          background: #f5f2ef;
          border-radius: 10px;
          font-size: 13px;
        }
        .ti-icon { font-size: 16px; }
        .ti-text { color: #1a1816; }
      </style>
    </template>
  };

  static edit = class Edit extends Component<typeof this> {
    <template>
      <div class='ti-edit'>
        <div class='ti-edit-field'>
          <label>Icon (emoji, e.g. 📚 👟 🎨)</label>
          <@fields.icon />
        </div>
        <div class='ti-edit-field'>
          <label>Text (e.g. "Return library book")</label>
          <@fields.text />
        </div>
      </div>
      <style scoped>
        .ti-edit {
          display: flex;
          flex-direction: column;
          gap: 10px;
          padding: 12px 14px;
          background: #faf8f6;
          border-radius: 8px;
        }
        .ti-edit-field { display: flex; flex-direction: column; gap: 3px; }
        .ti-edit-field label {
          font-size: 10px;
          font-weight: 700;
          text-transform: uppercase;
          color: #718096;
          letter-spacing: 0.5px;
        }
      </style>
    </template>
  };
}

// =========================================================
//   ParentDailySummary - the persistent card
// =========================================================

export class ParentDailySummary extends CardDef {
  static displayName = 'Parent Daily Summary';

  // ---- Identity / traceability ----
  @field studentSlug = contains(StringField);
  @field studentName = contains(StringField);
  @field studentGrade = contains(StringField);
  @field summaryDate = contains(DateField);
  @field sourceDailyCommunicationId = contains(StringField);
  @field sourceSkillCardId = contains(StringField);
  @field generatedAt = contains(DatetimeField);
  @field generatedBy = contains(StringField);

  // ---- AI-generated content ----
  @field greeting = contains(StringField);      // "Great Day!"
  @field moodEmoji = contains(StringField);     // single emoji
  @field todaysHighlights = containsMany(HighlightBlockField);
  @field whatWeDid = containsMany(TimelineEntryField);

  // ---- Manual / Phase 5 ----
  @field forTomorrow = containsMany(TomorrowItemField); // AI does NOT fill
  @field photoUrl = contains(StringField);
  @field photoCaption = contains(StringField);

  // ---- Workflow ----
  @field status = contains(StringField);        // 'draft' | 'sent'
  @field quickReply = contains(StringField);
  @field sentAt = contains(DatetimeField);
  @field sentToName = contains(StringField);    // "Ms. Green"

  // ---- Computed ----
  @field cardTitle = contains(StringField, {
    computeVia: function (this: ParentDailySummary) {
      const rawName = this.studentName || this.studentSlug || '';
      const name = rawName && !/\s/.test(rawName) && rawName.includes('-')
        ? rawName
            .split('-')
            .map((w: string) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
            .join(' ')
        : (rawName || 'Student');
      const dateStr = this.summaryDate
        ? new Date(this.summaryDate as any).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
          })
        : '';
      return dateStr ? `${name} Summary - ${dateStr}` : `${name} Summary`;
    },
  });

  // ---------------------------------------------------
  // Embedded - list preview
  // ---------------------------------------------------
  static embedded = class Embedded extends Component<typeof ParentDailySummary> {
    <template>
      <div class='pds-embed'>
        <div class='pds-embed-top'>
          <span class='pds-embed-name'>{{@model.studentName}}</span>
          <span class='pds-embed-date'>{{@model.summaryDate}}</span>
        </div>
        <div class='pds-embed-greeting'>
          <span>{{@model.greeting}}</span>
          <span class='pds-embed-mood'>{{@model.moodEmoji}}</span>
        </div>
        <div class='pds-embed-meta'>
          <span class='pds-embed-status status-{{@model.status}}'>{{@model.status}}</span>
          <span class='pds-embed-count'>
            {{@model.todaysHighlights.length}} highlights
          </span>
        </div>
      </div>
      <style scoped>
        .pds-embed {
          padding: 14px 16px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          font-family: system-ui, sans-serif;
        }
        .pds-embed-top {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          margin-bottom: 6px;
        }
        .pds-embed-name { font-weight: 600; color: #1a1816; font-size: 14px; }
        .pds-embed-date { font-size: 12px; color: #a0aec0; font-family: ui-monospace, monospace; }
        .pds-embed-greeting {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 13px;
          color: #2a9d8f;
          font-weight: 600;
          margin-bottom: 6px;
        }
        .pds-embed-mood { font-size: 16px; }
        .pds-embed-meta {
          display: flex;
          gap: 10px;
          align-items: center;
        }
        .pds-embed-status {
          font-size: 10px;
          padding: 2px 8px;
          border-radius: 999px;
          text-transform: uppercase;
          font-weight: 700;
          letter-spacing: 0.5px;
        }
        .status-draft { background: #fef5e7; color: #975a16; }
        .status-sent { background: #f0fff4; color: #22543d; }
        .pds-embed-count { font-size: 11px; color: #718096; }
      </style>
    </template>
  };

  // ---------------------------------------------------
  // Isolated - iPhone mobile view (mockup 8/9)
  // ---------------------------------------------------
  static isolated = class Isolated extends Component<typeof ParentDailySummary> {
    dashboardUrl = DASHBOARD_URL;

    // NOTE: Teacher corrections use Boxel's built-in pencil icon in the
    // card's top-right chrome. No custom edit button.

    get weekdayString() {
      if (!this.args.model?.summaryDate) return '';
      const d = new Date(this.args.model.summaryDate as any);
      return d.toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
      });
    }

    get displayStudentName() {
      const raw = String(this.args.model?.studentName ?? '').trim();
      if (!raw) return 'Student';
      if (raw.includes('-') && !/\s/.test(raw)) {
        return raw
          .split('-')
          .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
          .join(' ');
      }
      return raw;
    }

    <template>
      <div class='pds-stage'>
        <a class='pds-back' href={{this.dashboardUrl}}>← Back to Dashboard</a>
        <div class='pds-phone'>
          <div class='pds-notch'></div>
          <div class='pds-screen'>

            {{! ---- status bar ---- }}
            <div class='pds-statusbar'>
              <span class='pds-clock'>3:32</span>
              <span class='pds-signal'>
                <svg width='30' height='12' viewBox='0 0 30 12' fill='currentColor'>
                  <rect x='0' y='6' width='3' height='6'/>
                  <rect x='5' y='4' width='3' height='8'/>
                  <rect x='10' y='2' width='3' height='10'/>
                  <rect x='15' y='0' width='3' height='12'/>
                  <rect x='22' y='2' width='7' height='10' rx='1'/>
                </svg>
              </span>
            </div>

            {{! ---- header ---- }}
            <header class='pds-header'>
              <span class='pds-brand'>TRIBECA PREP</span>
              <div class='pds-hero'>
                <div class='pds-avatar'>
                  <svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                    <circle cx='12' cy='8' r='4'/>
                    <path d='M4 21c0-4 4-7 8-7s8 3 8 7'/>
                  </svg>
                </div>
                <div class='pds-hero-text'>
                  <h1 class='pds-hero-name'>{{this.displayStudentName}}'s Day</h1>
                  <p class='pds-hero-date'>{{this.weekdayString}}</p>
                </div>
                <div class='pds-greeting-chip'>
                  <span class='pds-mood'>{{@model.moodEmoji}}</span>
                  <span class='pds-greeting-text'>{{@model.greeting}}</span>
                </div>
              </div>
            </header>

            {{! ---- TODAY'S HIGHLIGHTS ---- }}
            {{#if @model.todaysHighlights.length}}
              <section class='pds-section'>
                <h2 class='pds-section-title'>TODAY'S HIGHLIGHTS</h2>
                <div class='pds-highlights'>
                  {{#each @model.todaysHighlights as |h|}}
                    <div class='pds-highlight pds-highlight-{{h.type}}'>
                      <div class='pds-highlight-icon'>
                        {{#if (eq h.type 'Academic')}}
                          <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                            <path d='M2 3h20v14H2z M2 21h20'/>
                          </svg>
                        {{else if (eq h.type 'Social')}}
                          <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                            <circle cx='9' cy='8' r='3'/>
                            <circle cx='17' cy='8' r='3'/>
                            <path d='M3 21c0-3 2-5 6-5s6 2 6 5M12 21c0-2 2-4 5-4s5 2 5 4'/>
                          </svg>
                        {{else}}
                          <svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'>
                            <circle cx='12' cy='12' r='9'/>
                            <path d='M12 6v6l4 2'/>
                          </svg>
                        {{/if}}
                      </div>
                      <div class='pds-highlight-body'>
                        <div class='pds-highlight-title'>{{h.title}}</div>
                        <div class='pds-highlight-desc'>{{h.description}}</div>
                      </div>
                    </div>
                  {{/each}}
                </div>
              </section>
            {{/if}}

            {{! ---- PHOTO FROM TODAY ---- }}
            {{#if @model.photoUrl}}
              <section class='pds-section'>
                <h2 class='pds-section-title'>PHOTO FROM TODAY</h2>
                <figure class='pds-photo'>
                  <img src={{@model.photoUrl}} alt={{@model.photoCaption}} />
                  {{#if @model.photoCaption}}
                    <figcaption>{{@model.photoCaption}}</figcaption>
                  {{/if}}
                </figure>
              </section>
            {{/if}}

            {{! ---- WHAT WE DID ---- }}
            {{#if @model.whatWeDid.length}}
              <section class='pds-section'>
                <h2 class='pds-section-title'>WHAT WE DID</h2>
                <div class='pds-timeline'>
                  {{#each @model.whatWeDid as |entry|}}
                    <div class='pds-timeline-row'>
                      <span class='pds-time'>{{entry.time}}</span>
                      <span class='pds-dot'></span>
                      <span class='pds-activity'>{{entry.activity}}</span>
                      {{#if entry.score}}
                        <span class='pds-score'>{{entry.score}}</span>
                      {{/if}}
                      {{#if entry.status}}
                        <span class='pds-status'>{{entry.status}}</span>
                      {{/if}}
                    </div>
                  {{/each}}
                </div>
              </section>
            {{/if}}

            {{! ---- FOR TOMORROW (manual) ---- }}
            {{#if @model.forTomorrow.length}}
              <section class='pds-section'>
                <h2 class='pds-section-title'>FOR TOMORROW</h2>
                <div class='pds-tomorrow'>
                  {{#each @model.forTomorrow as |item|}}
                    <div class='pds-tomorrow-item'>
                      <span class='pds-tomorrow-icon'>{{item.icon}}</span>
                      <span class='pds-tomorrow-text'>{{item.text}}</span>
                    </div>
                  {{/each}}
                </div>
              </section>
            {{/if}}

            {{! ---- Quick reply + Send ---- }}
            <section class='pds-reply-section'>
              <label class='pds-reply-label'>Quick reply to teacher</label>
              {{#if @model.quickReply}}
                <div class='pds-reply-filled'>{{@model.quickReply}}</div>
              {{else}}
                <div class='pds-reply-placeholder'>Thanks! Any questions?</div>
              {{/if}}
              {{#if (eq @model.status 'sent')}}
                <button type='button' class='pds-send-btn sent' disabled>
                  <svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='3'>
                    <path d='M5 12l5 5 9-11'/>
                  </svg>
                  Sent to {{@model.sentToName}}
                </button>
              {{else}}
                <button type='button' class='pds-send-btn' disabled>
                  Send to {{if @model.sentToName @model.sentToName 'Teacher'}}
                </button>
              {{/if}}
            </section>

            <div class='pds-home-indicator'></div>
          </div>
        </div>

        {{! ---- Generation metadata (outside the phone frame) ---- }}
        <details class='pds-meta'>
          <summary>Generation metadata</summary>
          <dl>
            <dt>Generated at</dt><dd>{{@model.generatedAt}}</dd>
            <dt>Model</dt><dd class='mono'>{{@model.generatedBy}}</dd>
            <dt>Source DC</dt><dd class='mono small'>{{@model.sourceDailyCommunicationId}}</dd>
            <dt>Playbook</dt><dd class='mono small'>{{@model.sourceSkillCardId}}</dd>
            <dt>Status</dt><dd>{{@model.status}}</dd>
          </dl>
        </details>
      </div>

      <style scoped>
        .pds-stage {
          padding: 32px 16px;
          background: #faf8f6;
          min-height: 100%;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 20px;
          font-family: system-ui, -apple-system, sans-serif;
        }
        .pds-back {
          align-self: flex-start;
          padding: 8px 14px;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          color: #4a5568;
          font-size: 12px;
          font-weight: 600;
          text-decoration: none;
          margin-left: max(0px, calc(50% - 190px));
        }
        .pds-back:hover {
          background: #faf8f6;
          border-color: #2a9d8f;
          color: #2a9d8f;
        }

        /* iPhone frame */
        .pds-phone {
          width: 380px;
          max-width: 100%;
          background: #1a1816;
          border-radius: 36px;
          padding: 6px;
          box-shadow: 0 20px 50px rgba(0, 0, 0, 0.15);
        }
        .pds-notch {
          height: 22px;
          display: flex;
          justify-content: center;
          align-items: flex-end;
          position: relative;
        }
        .pds-notch::after {
          content: '';
          width: 110px;
          height: 22px;
          background: #1a1816;
          border-radius: 0 0 14px 14px;
          position: absolute;
          top: 0;
        }
        .pds-screen {
          background: white;
          border-radius: 30px;
          overflow: hidden;
          padding-top: 8px;
          min-height: 700px;
          position: relative;
        }

        /* status bar */
        .pds-statusbar {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 6px 24px 12px;
          font-size: 13px;
          font-weight: 700;
          color: #1a1816;
        }
        .pds-signal { color: #1a1816; }

        /* header */
        .pds-header {
          padding: 0 20px 16px;
        }
        .pds-brand {
          font-size: 11px;
          font-weight: 700;
          color: #e05d50;
          letter-spacing: 0.8px;
          display: block;
          margin-bottom: 12px;
        }
        .pds-hero {
          display: flex;
          align-items: center;
          gap: 12px;
        }
        .pds-avatar {
          width: 44px;
          height: 44px;
          background: #2a9d8f;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          color: white;
          flex-shrink: 0;
        }
        .pds-hero-text { flex: 1; min-width: 0; }
        .pds-hero-name {
          margin: 0 0 2px;
          font-size: 20px;
          font-weight: 700;
          color: #1a1816;
        }
        .pds-hero-date {
          margin: 0;
          font-size: 12px;
          color: #8a8279;
        }
        .pds-greeting-chip {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 2px;
          padding: 8px 10px;
          background: #fef5e7;
          border-radius: 12px;
          flex-shrink: 0;
        }
        .pds-mood { font-size: 22px; line-height: 1; }
        .pds-greeting-text {
          font-size: 10px;
          color: #c08b30;
          font-weight: 700;
          white-space: nowrap;
        }

        /* sections */
        .pds-section {
          padding: 14px 20px;
        }
        .pds-section-title {
          margin: 0 0 10px;
          font-size: 11px;
          font-weight: 700;
          color: #8a8279;
          letter-spacing: 0.6px;
        }

        /* Highlights */
        .pds-highlights {
          display: flex;
          flex-direction: column;
          gap: 8px;
        }
        .pds-highlight {
          display: flex;
          align-items: flex-start;
          gap: 10px;
          padding: 12px 14px;
          border-radius: 12px;
        }
        .pds-highlight-Academic { background: #fdeceb; }
        .pds-highlight-Academic .pds-highlight-icon { color: #e05d50; }
        .pds-highlight-Academic .pds-highlight-title { color: #9a2d1f; }
        .pds-highlight-Social { background: #f1ebfb; }
        .pds-highlight-Social .pds-highlight-icon { color: #7c5fc4; }
        .pds-highlight-Social .pds-highlight-title { color: #553c9a; }
        .pds-highlight-Behavioral { background: #fef5e7; }
        .pds-highlight-Behavioral .pds-highlight-icon { color: #c08b30; }
        .pds-highlight-Behavioral .pds-highlight-title { color: #975a16; }
        .pds-highlight-icon {
          flex-shrink: 0;
          padding-top: 2px;
        }
        .pds-highlight-body { flex: 1; min-width: 0; }
        .pds-highlight-title {
          font-weight: 700;
          font-size: 14px;
          margin-bottom: 2px;
        }
        .pds-highlight-desc {
          font-size: 12px;
          color: #5c5650;
          line-height: 1.4;
        }

        /* Photo */
        .pds-photo {
          margin: 0;
          border-radius: 12px;
          overflow: hidden;
          background: #faf8f6;
        }
        .pds-photo img {
          width: 100%;
          display: block;
        }
        .pds-photo figcaption {
          padding: 10px 14px;
          font-size: 12px;
          color: #5c5650;
          font-style: italic;
        }

        /* Timeline */
        .pds-timeline {
          display: flex;
          flex-direction: column;
          gap: 2px;
        }
        .pds-timeline-row {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 6px 0;
          font-size: 13px;
        }
        .pds-time {
          color: #8a8279;
          font-family: ui-monospace, monospace;
          font-size: 11px;
          min-width: 36px;
        }
        .pds-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
          background: #2a9d8f;
          flex-shrink: 0;
        }
        .pds-activity { color: #1a1816; flex: 1; }
        .pds-score {
          background: #e8f6f4;
          color: #2a9d8f;
          font-family: ui-monospace, monospace;
          font-size: 11px;
          padding: 2px 6px;
          border-radius: 4px;
        }
        .pds-status {
          font-size: 11px;
          color: #7c5fc4;
          font-style: italic;
        }

        /* Tomorrow */
        .pds-tomorrow {
          display: flex;
          flex-direction: column;
          gap: 6px;
        }
        .pds-tomorrow-item {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 10px 14px;
          background: #faf8f6;
          border-radius: 10px;
          font-size: 13px;
          color: #1a1816;
        }
        .pds-tomorrow-icon { font-size: 16px; }

        /* Reply + Send */
        .pds-reply-section {
          padding: 14px 20px 20px;
          border-top: 1px solid #f5f2ef;
          margin-top: 8px;
        }
        .pds-reply-label {
          display: block;
          font-size: 11px;
          color: #8a8279;
          margin-bottom: 6px;
        }
        .pds-reply-placeholder,
        .pds-reply-filled {
          padding: 10px 14px;
          background: #faf8f6;
          border-radius: 10px;
          font-size: 13px;
          margin-bottom: 12px;
        }
        .pds-reply-placeholder { color: #a0aec0; font-style: italic; }
        .pds-reply-filled { color: #1a1816; }
        .pds-send-btn {
          width: 100%;
          padding: 14px;
          background: #e05d50;
          color: white;
          border: none;
          border-radius: 12px;
          font-size: 14px;
          font-weight: 700;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
        }
        .pds-send-btn.sent {
          background: #2a9d8f;
          cursor: default;
        }
        .pds-send-btn:disabled { opacity: 0.9; }

        .pds-home-indicator {
          height: 5px;
          width: 100px;
          background: #1a1816;
          border-radius: 3px;
          margin: 6px auto 12px;
        }

        /* Debug meta outside the phone */
        .pds-meta {
          max-width: 560px;
          width: 100%;
          font-size: 11px;
          color: #8a8279;
          background: white;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 12px 14px;
        }
        .pds-meta summary { cursor: pointer; font-weight: 600; }
        .pds-meta dl {
          margin: 10px 0 0;
          display: grid;
          grid-template-columns: 110px 1fr;
          gap: 4px 12px;
        }
        .pds-meta dt { color: #8a8279; }
        .pds-meta dd { margin: 0; color: #2d3748; word-break: break-all; }
        .pds-meta dd.mono { font-family: ui-monospace, monospace; }
        .pds-meta dd.small { font-size: 10px; }
      </style>
    </template>
  };
}

// =========================================================
//   generateParentSummary - AI translation helper
//
//   Input:  a DailyCommunication card (Phase 3 output, already reviewed)
//   Action: read dc.reviewedMarkdown + skillCard.compiledPrompt,
//           call Gemini once, parse JSON, build + save a new
//           ParentDailySummary card in parent-daily realm.
//   Output: savedCardId + parsed JSON + timing info
// =========================================================

export interface GenerateParentSummaryInput {
  dailyCommCard: any;   // DailyCommunication instance
  skillCard: any;       // parent-summary SkillCard instance
  commandContext: any;
  realmHref: string;
}

export interface GenerateParentSummaryResult {
  savedCardId: string;
  model: string;
  latencyMs: number;
  parsedJson: any;
}

export async function generateParentSummary(
  input: GenerateParentSummaryInput,
): Promise<GenerateParentSummaryResult> {
  const t0 = performance.now();

  // ---- 1. Extract playbook + source markdown ----
  const compiledPrompt = String(input.skillCard?.compiledPrompt ?? '').trim();
  const reviewedMarkdown = String(input.dailyCommCard?.reviewedMarkdown ?? '').trim();

  if (!compiledPrompt) {
    throw new Error(
      'SkillCard compiledPrompt is empty. Check the parent-summary SkillCard instance.',
    );
  }
  if (!reviewedMarkdown) {
    throw new Error(
      'DailyCommunication reviewedMarkdown is empty. Make sure the DC card is fully populated.',
    );
  }

  // ---- 2. Build system prompt ----
  const outputSchemaInstruction = `

---

## YOUR TASK

You will be given a reviewed Daily Communication card (the teacher version).
Rewrite it into a short, mobile-friendly Parent Summary card. This is a digest
for the parent to scan on their phone in 30 seconds. Follow the playbook above.

Return ONLY a valid JSON object matching the schema below. No markdown fences,
no commentary outside the JSON.

### OUTPUT SCHEMA

{
  "greeting":  "<short warm phrase with one emoji, 1-4 words, e.g. 'Great Day!', 'Wonderful Wednesday', 'Kindness Day'>",
  "moodEmoji": "<single emoji matching myDayWas: sun for Great, smile for Good, calm face for OK, muscle for Hard>",
  "todaysHighlights": [
    {
      "type":        "<one of: Academic | Social | Behavioral>",
      "title":       "<2-4 word title like 'Math Milestone!' or 'Kindness Win'>",
      "description": "<exactly ONE sentence, first-person student voice, 5-15 words>"
    }
  ],
  "whatWeDid": [
    {
      "time":     "<HH:MM in 24-hour if the source DailyCommunication has a time reference, else empty string>",
      "activity": "<short 1-3 word name, e.g. 'Math' not 'Direct Instruction math lesson 45'>",
      "status":   "<optional short descriptor: 'Great focus!', or empty string>",
      "score":    "<optional, only if the source had one: '18/20', '30 min', or empty string>"
    }
  ]
}

### RULES

1. Return 2-3 highlights maximum. Three is the ceiling.
2. Each highlight "description" is ONE sentence, 5-15 words, first-person student voice.
3. "whatWeDid" should include ALL activities from the DailyCommunication whatIWorkedOn array PLUS routine blocks (Homeroom, Lunch, etc.) from the schedule. Add check marks for completed items.
4. "activity" in whatWeDid should be a short 1-3 word label (e.g. 'DI Math', 'Reading', 'Lunch + Recess', 'Social Skills').
5. Include scores from the source (e.g. '4/5', '8/10') and add status comments for standout moments (e.g. 'Great focus!', 'Great participation!').
6. "greeting" and "moodEmoji" should reflect the overall feeling based on daySummary and myDayWas.
7. Do NOT generate any "for tomorrow" items - that field is filled manually by the teacher.
8. Never mention the student's name in the body text.`;

  const systemPrompt = compiledPrompt + outputSchemaInstruction;
  const userPrompt =
    'Here is the reviewed Daily Communication card. Generate the Parent Summary JSON:\n\n' +
    reviewedMarkdown;

  // ---- 3. Decide model ----
  const modelFromSkill = String(input.skillCard?.modelSize ?? '').trim();
  const model =
    modelFromSkill && modelFromSkill.startsWith('google/')
      ? modelFromSkill
      : 'google/gemini-2.0-flash-001';

  console.log(`[generatePS] model=${model}, sys=${systemPrompt.length} chars, usr=${userPrompt.length} chars`);

  // ---- 4. Call Gemini ----
  const requestBody = JSON.stringify({
    model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt },
    ],
    temperature: 0.5,
    max_tokens: 600,
  });

  const apiCall = new SendRequestViaProxyCommand(input.commandContext).execute({
    url: 'https://openrouter.ai/api/v1/chat/completions',
    method: 'POST',
    requestBody,
    headers: {
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://app.boxel.ai',
      'X-Title': 'Tribeca Prep Parent Summary Generator',
    },
  });

  const timeout = new Promise((_r, rej) =>
    setTimeout(() => rej(new Error('AI translate timed out after 30s')), 30000),
  );

  const response: any = await Promise.race([apiCall, timeout]);

  if (response?.response && !response.response.ok) {
    let bodyText = '';
    try { bodyText = await response.response.text(); } catch (_) {}
    throw new Error(
      `HTTP ${response.response.status}: ${response.response.statusText} body: ${bodyText.slice(0, 800)}`,
    );
  }

  // ---- 5. Unwrap response ----
  let data: any;
  try {
    if (response?.response?.text) {
      const raw = await response.response.text();
      data = JSON.parse(raw);
    } else if (response?.response?.json) {
      data = await response.response.json();
    } else {
      data = response;
    }
  } catch (_) {
    data = response;
  }

  let content: string =
    data?.choices?.[0]?.message?.content ??
    data?.response?.choices?.[0]?.message?.content ??
    data?.data?.choices?.[0]?.message?.content ??
    (typeof data?.response === 'string' ? data.response : '') ??
    '';

  if (!content && data) {
    try {
      const jsonStr = typeof data === 'string' ? data : JSON.stringify(data);
      const match = jsonStr.match(/"content"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      if (match) content = JSON.parse('"' + match[1] + '"');
    } catch (_) { /* ignore */ }
  }

  const clean = content
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```$/i, '')
    .trim();

  if (!clean) {
    throw new Error(
      `AI returned empty content. Response keys: ${Object.keys(data ?? {}).join(',')}`,
    );
  }

  let parsed: any;
  try {
    parsed = JSON.parse(clean);
  } catch (e) {
    throw new Error(
      `Failed to parse AI response as JSON: ${e}. Raw: ${clean.slice(0, 600)}`,
    );
  }

  console.log('[generatePS] parsed JSON', parsed);

  // ---- 6. Build ParentDailySummary card ----
  const pds = new ParentDailySummary();

  // Traceability - copy from source DC
  pds.studentSlug = String(input.dailyCommCard?.studentSlug ?? '');

  const rawStudentName = String(input.dailyCommCard?.studentName ?? '');
  const looksLikeSlug =
    rawStudentName && !/\s/.test(rawStudentName) && rawStudentName.includes('-');
  pds.studentName = looksLikeSlug
    ? rawStudentName
        .split('-')
        .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ''))
        .join(' ')
    : rawStudentName;

  const dcDate = input.dailyCommCard?.snapshotDate;
  if (dcDate instanceof Date) {
    (pds as any).summaryDate = dcDate;
  } else if (typeof dcDate === 'string') {
    (pds as any).summaryDate = new Date(dcDate);
  } else {
    (pds as any).summaryDate = new Date();
  }

  pds.sourceDailyCommunicationId = String(input.dailyCommCard?.id ?? '');
  pds.sourceSkillCardId = String(input.skillCard?.id ?? '');
  (pds as any).generatedAt = new Date();
  pds.generatedBy = model;

  // AI-generated content
  pds.greeting = String(parsed?.greeting ?? '');
  pds.moodEmoji = String(parsed?.moodEmoji ?? '');

  // containsMany: populate as plain arrays of FieldDef instances
  const highlightsRaw = Array.isArray(parsed?.todaysHighlights)
    ? parsed.todaysHighlights
    : [];
  (pds as any).todaysHighlights = highlightsRaw.map((h: any) => {
    const item = new HighlightBlockField();
    item.type = String(h?.type ?? 'Academic');
    item.title = String(h?.title ?? '');
    item.description = String(h?.description ?? '');
    return item;
  });

  const timelineRaw = Array.isArray(parsed?.whatWeDid) ? parsed.whatWeDid : [];
  (pds as any).whatWeDid = timelineRaw.map((t: any) => {
    const item = new TimelineEntryField();
    item.time = String(t?.time ?? '');
    item.activity = String(t?.activity ?? '');
    item.status = String(t?.status ?? '');
    item.score = String(t?.score ?? '');
    return item;
  });

  // forTomorrow: empty (teacher will fill manually in Phase 5)
  (pds as any).forTomorrow = [];

  // Manual / Phase 5
  pds.photoUrl = '';
  pds.photoCaption = '';

  // Workflow state
  pds.status = 'draft';
  pds.quickReply = '';
  pds.sentToName = 'Ms. Green'; // placeholder, will be real teacher name in Phase 5

  // ---- 7. Save to parent-daily realm ----
  const { default: SaveCardCommand } = await import(
    '@cardstack/boxel-host/commands/save-card'
  );

  const saveResult: any = await new SaveCardCommand(input.commandContext).execute({
    card: pds,
    realm: input.realmHref,
  });

  const savedCardId =
    saveResult?.savedCard?.id ?? saveResult?.id ?? (pds as any)?.id ?? '';

  const latencyMs = Math.round(performance.now() - t0);
  console.log(`[generatePS] saved PDS id=${savedCardId} in ${latencyMs}ms`);

  return {
    savedCardId,
    model,
    latencyMs,
    parsedJson: parsed,
  };
}
